class RouteConstants {
  static const String aboutScreen = '/about-screen',
      downloadsScreen = '/downloads-screen',
      studentLifeScreen = '/student-life-screen',
      contactScreen = '/contact-screen',
      academicsScreen = '/academics-screen',
      coursesScreen = '/courses-screen',
      viewProfileScreen = '/view-profile-screen',
      syllabusScreen = '/syllabus-screen',
      facultyScreen = '/faculty-screen',
      settingsScreen = '/settings-screen',
      courseDetailScreen = 'course-detail-screen',
      libraryScreen = 'library-screen',
      departmentScreen = 'department-screen',
      universityDataScreen = 'unversity-data-screen',
      collegeNoticeScreen = 'college-notice-screen',
      viewPdfScreen = 'view-pdf-screen',
      enquiryScreen = 'enquiry-screen',
      photoGalleryScreen = 'photo-gallery-screen',
      facilitiesScreen = 'facilities-screen',
      aboutUsScreen = 'about-us-screen',
      authorityDetailScreen = 'authority-detail-screen',
      missionVisionScreen = 'mission-vision-screen',
      developerScreen = 'developer-screen';
}
